# -*- coding: utf-8 -*-
"""assignment 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11UozwH2oXvlnvP6ZhpEm77SkPCHF0hKZ
"""

#Write a program to print all even numbers between 1 and 30 (inclusive).
for i in range(1,31):
  if i%2 == 0:
    print(i)

#Create a program that calculates the sum of squares of the first 10 natural numbers using a for loop.
result = 0
for i in range(1,11):
  result = result + i ** 2
print(f"sum of squares of the first 10 natural numbers is {result} ")

#Write a program that prints a multiplication table for a user-defined number from 1 to 12.
number = int(input("enter number for multipication table : "))
for i in range(1,13):
  print(f"{number} * {i} = {number * i}")

#Develop a program that outputs the first 15 numbers in the Fibonacci sequence using a for loop.
a = 0
b = 1
print(a)
print(b)
for i in range(13):
  c = a + b
  print(c)
  a = b
  b = c

#Develop a program that outputs the first 15 numbers in the Fibonacci sequence using a for loop.
a = 0
b = 1
for i in range(15):
  print(a, end=" ")
  a, b = b, a + b

#Using a for loop, print the name "Hello" five times.
for i in range(5):
  print("hello")

#Write a program to find the maximum number in a list of integers using a for loop.
num = [200,40,6,10,3,18,5]
max = 0
for i in num:
  a = i
  if a > max:
    max = a
  else:
    max = max
print(f"the maximum number in the given list is : {max}")

#Create a program to print the factorial of numbers from 1 to 5 using a for loop.
fact = 1
for i in range(1,6):
  fact = fact * i
print(f"the factorial from 1 to 5 number is : {fact}")

#Write a program that prints all the characters in a given string, each on a new line, using a for loop.
a = input("enter the string")
for i in a:
  print(i)

#Design a program using a while loop that asks users to enter their age until they enter a valid age (greater than 0).
age = int(input("enter your age : "))
valid_age = 24
while age != valid_age  :
  age = int(input("enter age : "))
print(f"your age is : {age}")

#Write a program that counts down from 20 to 1 using a while loop.
num = 20
while num != 0:
  print(num)
  num = num -1

#Create a program that keeps asking the user for a password until they input the correct password.
correct_password = "1234rbt"
password = input("enter password : ")
while password != correct_password:
  password = input("enter correct password")
print("successful")

#Develop a program that reads numbers from the user until they enter zero and then prints the sum of the entered numbers.
number = int(input("enter the number : "))
sum = 0
while number != 0:
  sum = sum + number
  print(f"{sum}")
  number = int(input("enter the number"))
print("terminated")

#Using a while loop, generate and print the first 10 powers of 2.
power = 0
count = 0
while count < 10:
  print(2 ** power)
  count = count + 1
  power = power + 1

#Write a program that continues to ask for user input until they type "quit", then prints a message.
a = input("enter something :")
while a != "quit":
  a = input("enter something :")
print(f"you enter quit")

# Create a simple guessing game where the user keeps guessing a number (between 1 and 100) until they get it right.
number = 24
num = int(input("guess the number : "))
if num <= 100 and num >= 1:
  while num != 24:
     num = int(input("guess the number : "))
  print(f"you have guess the correct number that is : {num}")
else:
   print("enter number between 1 to 100 only ")

# Develop a program that uses a while loop to print the numbers from 1 to 50
# that are divisible by 4.
num = 1
while num < 50:
  if num % 4 == 0:
    print(num)
  num = num + 1