# -*- coding: utf-8 -*-
"""Data Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eewiWiwCG9FcNB8p_GccBaPRYd88_0Ta
"""

import pandas as pd
import numpy as np
import seaborn as sns #data visualizaton -2D interactive
import plotly.express as px
import plotly.graph_objects as go
import plotly.figure_factory as ff
from plotly.subplots import make_subplots # daya visualization - 3D interative
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
# import matplotlib
# plt.style.use('ggplot')
# from scipy.stats import norm
# from sklearn.preprocessing import StandardScaler
# from scipy import stats
# import warnings
# warnings.filterwarnings('ignore')
df=pd.read_csv("/content/heart_disease_uci.csv")

df

df.isnull()

df.isnull().sum()

df.dropna() #dropping all the NaN value row

top_leagues=df["cp"].value_counts()
top_leagues

top_leagues=df["cp"].value_counts().nlargest(4).index
top_leagues

# scatter plot= 2 relation observation . basically used in linear regression .. to show relation between 2 data
# x and y and numeric data

# isin()= pandas filter tool
# hue=as a key in data,, variable lai group garxa ani automatic different color set garxa,,categotical and numerical

plt.figure(figsize=(15,6))
sns.scatterplot(x="age",y="chol",data=df[df['cp'].isin(top_leagues)],hue="cp")
plt.title("Heart Disease by Age Chol and Chest Pain 4")
plt.xlabel("Age of the patients")
plt.ylabel("Cholestrol of the patients")
plt.legend(title="Different Chest Pain",loc="upper right")
plt.show()

fig=px.scatter(df,x="chol",y="age",color="sex")
fig.update_layout(width=1000,height=600)
fig.update_layout(title_text="Scatter plot of Cholestrol vs Age (colored by Sex)")
fig.show()

# offline version  extra package
from plotly.offline import iplot

fig=px.box(x=df["chol"],
           labels={"x":"Cholestrol"},
           title='Box Plot of Cholesterol')
fig.update_layout(width=1000,height=600)
iplot(fig)

fig=px.scatter(df,x="ca",y="age",color="cp")
fig.update_layout(width=1000,height=600)
fig.update_layout(title_text="Scatter plot of ChestPain")
fig.show()

from plotly.offline import iplot

fig=px.box(x=df["ca"],
           labels={"x":"Ca"},
           title='Box Plot of CA')
fig.update_layout(width=1000,height=600)
iplot(fig)

fig=px.bar(df,x="age",y="chol",hover_data=["oldpeak"],color="sex",height=400)
fig.show()

fig=px.bar(df,x="age",y="ca",hover_data=["chol"],color="sex",height=400)
fig.show()

