# -*- coding: utf-8 -*-
"""Day3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1na4V1cAl_0wd8YjVu9V2Quyiq7ytIJV2
"""

# [] Manupulation
# : or operator
# inclusive exclusive

a="ram"
b=  5

a+str(b)

# string membership'
#sub string " "
sentence="I love python"
"love" in sentence

# strint iteration (1 by 1 process)
word='Pokhara'
for i in word:
  print(i)
  print(i , end='')

favorite_fest=input('Enter your favorite festival: ')
Destination_fest_celebrated=input('Enter the best destination you have celebrated this festival: ')
method=input('What do you do to celebrate this festival: ')
custom=input('what custom do you wear in this festival: ')
food=input('What do you eat in this festival: ')
technology=input('Name 1 modern technology do you use in this festival: ')
impact1=input('Name one effect of this festival: ')
impact2=input('Name another effect of this festival: ')
impact3=input('Name another effect of this festival: ')

print(f'My favorite festival is {favorite_fest} and best destination i have celebrated this festival is {Destination_fest_celebrated} and the reason behind it is we get {method}. We wear {custom} in this festival. We eat{food} in this festivl. The modern technology like {technology} is used in this festival.It has alot of advantanges in life like listed below:\n1.{impact1}\n2.{impact2}\n3.{impact3}')

