# -*- coding: utf-8 -*-
"""DDLJ meets Squid Game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GzRUlhIaokMkCapNsU9icPQVRpS7xtkg
"""

import numpy as np
def one():
    print("Win Simran’s Father’s Approval!Be Careful Because He is Mucambo as Well!!!")
    print("Give right answer to get the exact location of Simran")
    count = 0

    answer1 = input("Question 1: What is the essence of true love? ").lower()
    if "trust" in answer1 or "sacrifice" in answer1 or "care" in answer1 or "respect" in answer1:
        print("Ohh! You didnt get the beer before but you get the right answer.")
        count += 1
    else:
        print("You are Totally wrong. I guess you have to return to London single hahahah")

    answer2 = input("Question 2: Name an iconic moment from DDLJ. ").lower()
    if "india train station" in answer2 or "london beer buying" in answer2 or "train miss in london" in answer2:
        print("Not again! Kuljit i think i have to say sorry")
        count += 1
    else:
        print("Wrong again!!Mucambo Khus Huwa hahaha")

    answer3 = input("Question 3: How will you respect our traditions? ").lower()
    if "by following family culture" in answer3 or "by respecting family seniours" in answer3:
        print("Simran is all your beta raj..I am ready to say jaa simran jaa jii le apni jindagi")
        count += 1
    else:
        print("Yeh adaalat hai, koi mandir ya dargah nahi jahan mannatein aur muraadein poori hoti hai!! go back to london now")

    print()
    print()
    print()

    if count == 3:
        print("Main to samajhta tha ki duniya mein mujhse bada kameena aur koi nahin hai, lekin tumne ain mauke par aisa kameenapan dikhaya ki hum tumhare kameenepan ke ghulam ho gaye hain")
        print()
        print()
        print("Cross the Glass Bridge!Aadmi ke pas dimag ho to wo apna dard bhi bech sakta hai")
        print("Time to prove!!")
        print()
        print()
        bridge = np.random.choice(['L', 'R'],5)
        print("The Bridge has 5 stage to complete Raj!!")
        for i in range(1,6):
          guess=input("Enter L or R= ").upper()
          if guess == bridge[i]:
            print("Congrats you proved it!!")
            print("Kehte hain agar kisi cheez ko dil se chaho … to poori kainath use tumse milane ki koshish mein lag jaati hai” #GoodLuck")
            print("Next Question")
          else:
            print("Bad choice Wrong step!!")
            print("Dil toh har kisi ke paas hota hai, lekin sab Dilwale nahi hote!")
            print(f"Sorry Raj!! Diljit will Marry simran and you have to return back to london.")
    else:
        print("Upar wala wrong ho sakta hai lekin Dong kabhi wrong nahi hota..jawo raj london wapas")
one()