# -*- coding: utf-8 -*-
"""Homework for and while loop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RI4DcqGEW3E5dyl8bxqtk0u5JDadkHvq
"""

# Homework - Complete and submit it on friday

# For Loop Questions
# Write a program to print all even numbers between 1 and 30 (inclusive).
# Create a program that calculates the sum of squares of the first 10 natural numbers using a for loop.
# Write a program that prints a multiplication table for a user-defined number from 1 to 12.
# Develop a program that outputs the first 15 numbers in the Fibonacci sequence using a for loop.
# Using a for loop, print the name "Hello" five times.
# Write a program to find the maximum number in a list of integers using a for loop.
# Create a program to print the factorial of numbers from 1 to 5 using a for loop.
# Write a program that prints all the characters in a given string, each on a new line, using a for loop.
# While Loop Questions
# Design a program using a while loop that asks users to enter their age until they enter a valid age (greater than 0).
# Write a program that counts down from 20 to 1 using a while loop.
# Create a program that keeps asking the user for a password until they input the correct password.
# Develop a program that reads numbers from the user until they enter zero and then prints the sum of the entered numbers.
# Using a while loop, generate and print the first 10 powers of 2.
# Write a program that continues to ask for user input until they type "quit", then prints a message.
# Create a simple guessing game where the user keeps guessing a number (between 1 and 100) until they get it right.
# Develop a program that uses a while loop to print the numbers from 1 to 50 that are divisible by 4.

# For Loop
for i in range(1,31):
  if i % 2 == 0:
    print(i)
  else:
    exit()

sum=0
for i in range(1,10):
  sum+=i
print(sum)

table=int(input("enter a number from 1 to 12= "))
if table>12 or table<1:
  print("invalid number")
else:
  for i in range(1,11):
   print(f'{table} * {i} = {table*i}')

# 011235
a=0
b=1
for i in range(16):
  print(a)
  c=a+b
  a=b
  b=c
  c=a

for i in range(6):
  print('Hello')

a=int(input('enter how many number you want to enter: '))
max = 0
for i in range(a):
  b=int(input('enter a number= '))3
  if b>max:
    max=b
  else:
    exit()
print(max)

# factorial number
a=int(input('enter a number= '))
fact=1

for i in range(1,a+1):
  fact  = fact*i
print(fact)

a=input('enter a string= ')
for i in a:
  print(i)

# While Loop
age=int(input("enter a valid age= "))
while age<=0:
  print("invalid age")
  age=int(input("enter a valid age= "))
else:
  print("valid age")

a=20
while a>=1:
  print(a)
  a -=1

password="Nepal"
passw=input("enter a password= ")
while passw != "Nepal":
  print("Incorrect password")
  passw=input("enter a password= ")
else:
  print("correct password")

a=int(input('enter a number= '))
sum=0
while a!=0:
  sum+=a
  a=int(input('enter a number= '))
else:
  print(sum)

a=2
b=0
while b<10:
  print(f"{a}^{b} = {a**b}")
  b+=1

a=input('enter a word= ')

while a!="quit":
  print("please re_enter new word")
  a=input('enter a new word= ')
else:
  print("Well Done!! Right Answer is quit.")

a=50
b=int(input('Guess a number= '))
while b!=a:
  if b>100:
    print('Guess below 100')
  elif b>a:
    print("Guess lower number")
  else:
    print('Guess higher number')
  b=int(input('Guess a  new number= '))
else:
  print(f'Well Done!!. {b} is right guess')

a=1
while a <=50:
  if a%4==0:
    print(a)
  else:
    exit()
  a+=1

b=[1,3,[4,"Kusum",["cat","bat"]]]
b[2][2][1]

a=[] #empty list
a.append(1)
a
a.append(2)
a
a[0]=6
a.insert(0,3)
a

patients = ["John", "Alice", "Mark", "Sophia"]
new=input("enter a new patient= ")
patients.insert(1,new)
patients

fruits = ["Apple", "Banana", "Cherry"]
additional_fruits= ["Orange", "Mango", "Grapes"]
fruits.extend(additional_fruits)
fruits

subjects = ["Math", "Physics", "Chemistry", "Biology"]
a=subjects.index("Chemistry")
print(f"Chemistry is at index {a}.")

a=[1,2,3]
a

a[1]=25
a

a=[10,30,20,30,40,50]
a.remove(30)
a
abb=a.pop(1)
print(a)

del a[0]
a

students = ["Sita", "Ram", "Hari", "Gita", "Krishna"]
students.append("Bikash")

students.insert(1,"Krishna")
students
students.remove("Krishna")

students.remove("Gita")
students

del students[2]
students

