# -*- coding: utf-8 -*-
"""inheritance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmuTvVuV3dDfyCEVHFC_OsFyR7sKg5GI
"""

# class A:
#     pass

# class B(A):
#     pass

# obj = B()

class A:
    def __init__(self):
        self.name = input("Enter name = ")
        self.add = input("Enter add = ")

class B(A):
    def info(self):
        print(f"Hello my name is {self.name}. I am from {self.add}")

obj = B()
obj.info()

class A:
    def __init__(self,name,add):
        self.name = name
        self.add = add

class B(A):
    def info(self):
        print(f"Hello my name is {self.name}. I am from {self.add}")

name = input("Enter name = ")
add = input("Enter add = ")

obj = B(name,add)
obj.info()

class A:
    pass

class B(A):
    pass

class C(B):
    pass

obj = C()

class A:
    pass

class B:
    pass

class C(A,B):
    pass

obj = C()

class A:
    def __init__(self,add):
        self.add = add
    def address(self):
        print(f"I am from {self.add}")

class B(A):
    def __init__(self,age,add):
        self.age = age
        A.__init__(self,add)
    def ages(self):
        print(f"I am from {self.add} I am {self.age}")

class C(B):
    def __init__(self,name,age,add):
        self.name = name
        B.__init__(self,age,add)

    def info(self):
        print("Hello World I am {self.name}.
              I am from {self.add} I am {self.age}")

obj = C("Ram",34,"Kathmandu")

class A:
    def __init__(self,add):
        self.add = add
    def address(self):
        print(f"I am from {self.add}")

class B:
    def __init__(self,age):
        self.age = age
    def ages(self):
        print(f"I am from I am {self.age}")

class C(A,B):
    def __init__(self,name,age,add):
        self.name = name
        B.__init__(self,age)
        A.__init__(self,add)

    def info(self):
        print(f"Hello World I am {self.name}. I am from {self.add} I am {self.age}")

obj = C("Ram",34,"Kathmandu")
obj.info()

class A:
    def __init__(self):
        self.add = "Kathmandu"
    def a(self):
        pass
class B:
    def __init__(self):
        self.age = 40
    def b(self):
        pass

class C(A,B):
    def __init__(self):
        A.__init__(self)
        B.__init__(self)
    def info(self):
        print(f"Hello I am {self.age}. I am from {self.add}")

obj = C()
obj.info()

#Public members
class Info:
    def __init__(self,name,age,add):
        self.name = name
        self.age = age
        self.add = add

obj = Info("Ram",34,"Kathmandu")
print(obj.name)
print(obj.age)
print(obj.add)

#Protected members
class Info:
    def __init__(self,name,age,add):
        self._name = name
        self._age = age
        self._add = add

obj = Info("Ram",34,"Kathmandu")
print(obj._name)
print(obj._age)
print(obj._add)

#Private members
class Info:
    def __init__(self,name,age,add):
        self.__name = name
        self.__age = age
        self.__add = add

obj = Info("Ram",34,"Kathmandu")
print(obj.__name)
print(obj.__age)
print(obj.__add)

#Private members
class Info:
    def __init__(self,name,age,add):
        self.__name = name
        self.__age = age
        self.__add = add

obj = Info("Ram",34,"Kathmandu")
print(obj._Info__name)
print(obj._Info__age)
print(obj._Info__add)

class A:
    def __init__(self,name,age,add):
        self.name = name
        self._age = age
        self.__add = add
    def a(self):
        print(f"Hello world I am {self.name}. I am from {self.__add} I am {self._age}")

class B(A):
    def info(self):
        print(f"Hello my name is {self.name}.I am {self._age}")

name = input("Enter name = ")
age = int(input("Enter age = "))
add = input("Enter add = ")

obj = B(name,age,add)
obj.info()
obj.a()

class A:
    def __init__(self,add):
        self._add = add
    def address(self):
        print(f"I am from {self.add}")

class B:
    def __init__(self,age):
        self._age = age
    def ages(self):
        print(f"I am from I am {self.age}")

class C(A,B):
    def __init__(self,name,age,add):
        self.__name = name
        B.__init__(self,age)
        A.__init__(self,add)

    def info(self):
        print(f"Hello World I am {self.__name}.
              I am from {self._add} I am {self._age}")

obj = C("Ram",34,"Kathmandu")
obj.info()

class A:
    def __init__(self,name,add):
        self.name = name
        self.add = add
    def a(self):
        return f"Hello my name is {self.name}"

class B(A):
    def info(self):
#         print(super().a())
        print(super().a(),f"I am from {self.add}")

name = input("Enter name = ")
add = input("Enter add = ")

obj = B(name,add)
obj.info()

[['Ram',34],
['Shyam',34]]

# class A:
#     pass

# class B:
#     pass

# class C(A,B):
#     pass

# obj = C()