# -*- coding: utf-8 -*-
"""newnumpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15t8Ux9eCBy4i7R35Wnx9o5TEQ-ZmWKHm
"""

import numpy as np
a=np.random.randint(1,100,size=(10))

a[a<=50]

b=np.random.randint(1,9,(4,4))
print(b)
b[:,1:3]

b[:3,2:4]

[b[0,0],b[1,1],b[2,2],b[3,3],b[0,3],b[1,2],b[2,1],b[3,0]]

[b[0,0],b[1,0],b[2,0],b[3,0],b[3,1],b[3,2]]

teama=np.random.randint(1,100,(5,))
teamb=np.random.randint(1,100,(5,))
a=np.sum(teama)
b=np.sum(teamb)
if a>b:
    print("a won")
elif a<b:
    print("b won")
else:
    print("tie")

marblea=np.random.randint(-5,6,(5,))
marbleb=np.random.randint(-5,6,(5,))
totala=np.sum(marblea)
totalb=np.sum(marbleb)
print(totala,totalb)
if totala>totalb:
    print("a won")
elif totala<totalb:
    print("b won")
else:
    print("tie")

import numpy as np
for i in range(1,11):
  game=np.random.randint(0,2,(10,))
  a=int(input(f"Take the step{i} from 0 to 9= "))
  if game[a]==0:
    print("Dead")
    break
  else:
    print("Alive")

