# -*- coding: utf-8 -*-
"""Pandas hw.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lYugS_S3OfJrcl3xnV3oJ56gr47U-Lhd
"""



from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df =  pd.read_csv('/content/drive/MyDrive/TECHAXIS IRIS SURVEY/Iris.csv')
df

df.head(10) # first 10 datasets

df.tail(5) #last 5 datasets

df.shape #total rows and column

df.info() #information

df.describe() #summary statistics for the numerical columns.

min_sepal_length = df["SepalLengthCm"].min() #minimum value

min_sepal_length

max_sepal_length = df["SepalLengthCm"].max() # maximum value

max_sepal_length

mean_sepal_length = df["SepalLengthCm"].mean() # Average

mean_sepal_length

df = (df[df["SepalLengthCm"] > 6.0])
 df

filtered_df = df[(df["Species"] == "Iris-virginica") & (df["PetalWidthCm"] > 2.0)]      # displaying all rows
filtered_df

max_sepal_width = df["SepalWidthCm"].max() #
max_sepal_width_row = df[df["SepalWidthCm"] == max_sepal_width]
max_sepal_width_row

df[(df['SepalWidthCm'] < 3.0) & (df['PetalLengthCm'] > 4.0)]

a=df[(df['Species'] == 'Iris-setosa') & (df['SepalLengthCm'] > 4.5) & (df['SepalLengthCm'] < 5.5)]
a

average_petal_length = df['PetalLengthCm'].mean()
print(f"\nThe average PetalLengthCm for the dataset is {average_petal_length:.2f} cm.")

(df['Species'] == 'Iris-versicolor').value_counts()

b=df['SepalLengthCm'].max()
b

c=df.loc[df['SepalWidthCm'] == (df['SepalWidthCm'].max())]
c

df['Species'].unique()

df['Species'].value_counts()

