# -*- coding: utf-8 -*-
"""Pandas part 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gAX2hpRKxhO7MK19VjGGhhAfhhS0jIF8
"""

# Data manipulation - Data analysis to take out insite from data, Data management
# Data structure - Series , Dataframes

# Series = 1 dimension labeled array (any datatype can be hold, similar to list same[bracket])
# Dataframes= 2 dimension


from google.colab import drive
drive.mount("/content/drive") # to connect drive to google colab

# pip install pandas
import pandas as pd
data = pd.Series(["nepal",0.5,0.75,1.0])
print(data)
print()

a={"name":["ram","shyam","hari"],
   "age":[22,23,24],
   "score":[98,97,99]}
df=pd.DataFrame(a)
print(df)

df =pd.read_csv("/content/drive/MyDrive/Techaxis/survey_results_public (2).csv")
schema_df=pd.read_csv("/content/drive/MyDrive/Techaxis/survey_results_schema (2).csv")
df

# df.to_csv(new.csv,index=False) = to create csv file
df.shape # to dispaly row and column

df.info()

df.describe()

df["Hobbyist"]

df["Hobbyist"].value_counts()

df["Gender"]

df["Gender"].value_counts()

# indexing and selecting data
# .loc(Local based indexing) = int variable = more filter than iloc
# iloc(Interger based position) = primary integer position based =int

df.loc[0]

df.loc[0,"Hobbyist"]

df.loc[0:2,"Hobbyist"]

df.loc[0:100,"Hobbyist"]

df.loc[0:100,"Hobbyist":"Employment"]

# type of data analysis
schema_df

schema_df=pd.read_csv("/content/drive/MyDrive/Techaxis/survey_results_schema (2).csv", index_col="Column")
schema_df

schema_df.loc["Respondent","QuestionText"]

schema_df.loc["Hobbyist","QuestionText"]

df =pd.read_csv("/content/drive/MyDrive/Techaxis/survey_results_public (2).csv", index_col="Respondent")
df

# reverse
df.sort_index(ascending=False)

df['Country'] == "Nepal"

(df['Country'] == "Nepal").value_counts()

df[df['Country'] == "Nepal"]

filter_nepal=df['Country'] == "Nepal"
df[filter_nepal]

